project_name: parsec
strict: false
module:
    base_module: bioblend.toolshed
    instance_cls: "<class 'bioblend.toolshed.ToolShedInstance'>"
    instance_func: ToolShedInstance
    prefix: toolshed_
    instance_args:
        - "http://localhost:8080"
        - "API_KEY"

    ignore:
        top_attrs:
            - base_url
            - client
            - default_params
            - get_retry_delay
            - json_headers
            - key
            - make_delete_request
            - make_get_request
            - make_patch_request
            - make_post_request
            - make_put_request
            - max_get_attempts
            - max_get_retries
            - set_retry_delay
            - timeout
            - url
            - verify
        funcs:
            - histories.download_dataset
            - histories.get_current_history
            - set_max_get_retries
            - get_max_get_retries
            - set_get_retry_delay
            - show_stderr
            - show_stdout
            - client
            - base_url
            - default_params
            - get_retry_delay
            - set_retry_delay
            - json_headers
            - key
            - set_get_retry_delay
            - set_max_get_retries
            - get_retry_delay
            - max_get_retries
            - make_delete_request
            - make_get_request
            - make_post_request
            - make_put_request
            - max_get_retries
            - max_get_attempts
            - url
            - verify

documentation: |
    parsec is a set of wrappers for BioBlend's API. It builds a set of small,
    useful utilities for talking to Galaxy servers. Each utility is implemented as
    a subcommand of ``parsec``. This section of the documentation
    describes these commands.
